name: Vue-Test-CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8
    - name: npm install, build, and test
      run: |
        npm install
        npm run build:test --if-present
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        # The name of the image you would like to push
        name: ${{secrets.DOCKER_PROGRAM}}
        # The login username for the registry
        username: ${{secrets.DOCKER_USERNAME}}
        # The login password for the registry
        password: ${{secrets.DOCKER_PASSWORD}}
          # Use registry for pushing to a custom registry
        registry: ${{secrets.DOCKER_REGISTRY}}
  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker stop $(docker ps --filter ancestor=${{ secrets.DOCKER_REPOSITORY }} -q)
            docker rm -f $(docker ps -a --filter ancestor=${{ secrets.DOCKER_REPOSITORY }}:latest -q)
            docker rmi -f $(docker images ${{ secrets.DOCKER_REPOSITORY }}:latest -q)
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
            docker pull ${{ secrets.DOCKER_REPOSITORY }}:latest
            docker run -d -p 8000:4000 ${{ secrets.DOCKER_REPOSITORY }}:latest
